language: node_js
node_js:
  - "stable"
before_script:
  - "npm config set registry https://registry.npm.taobao.org"
  - "npm install"
install:
  - npm install
script: npm run test
cache:
  directories:
    - node_modules
env:
  - CI=true
