language: node_js
node_js:
  - "stable"
before_install:
  - "npm config set registry https://registry.npm.taobao.org"
  - "npm config get registry"
  - "rm -rf node_modules"
  - "npm install"
install:
  - npm install
script: npm run test
cache:
  npm: false
env:
  - CI=true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: storybook
