language: node_js
node_js:
  - "stable"
before_script:
  - "npm config set registry https://registry.npm.taobao.org"
  - "rm -rf node_modules"
  - "npm install"
install:
  - npm install
script: npm run test
cache:
  npm: false
env:
  - CI=true
